### ISSUE TITLE
Buidler plugin fails if x.open.aragonpm.eth is used

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1352]
To reproduce, use token-wrapper.open.aragonpm.eth in test/projects/token-wrapper/arapp.json's default appName.

**Comment by sohkai** [comment]
Does `x.hatch.aragonpm.eth` work?

The problem is probably because we only deploy the base `aragonpm.eth` registry; if the app uses a different one, we will need to continue deploying more `aragonpm.eth` registries on top of `aragonpm.eth`. We should only support `open` and `hatch`; anything else we should warn.
