### ISSUE TITLE
Client doesn't re-download if initial download attempt times out

### ISSUE THREAD

**Issue by topocount** [aragon/aragon-cli#139]
When running `npm run start:kit` in an app under development for the first time, and the wrapper files and/or dependencies fail to download (due to timeout in my case), the missing files won't download (and thus the build will fail) unless the ~/.aragon/wrapper-xxxxxxx directory and its contents are deleted.

It might be good to incorporate a checksum (or whatever is standard practice) to ensure that all dependencies have been downloaded before the environment is built.

**Comment by izqui** [comment]
Thanks for reporting this, glad you figured out how to fix it!

I think checksumming all the dependencies is going to be a source of false positives, given the randomness usually involved with NPM. I think the best way forward is to try to catch this error from the CLI and let users know how they can fix or delete `~/.aragon/wrapper-xxxx` and tell the user to try again (however this wouldn't allow for manual retries and could be a source of frustration).

Do you remember if the CLI detected that installing the dependencies timed out? Did it then continue running or did you manually did `aragon run` again and it didn't try to install the dependencies again?

**Comment by 0xGabi** [comment]
@dapplion @ajsantander is this still relevant during `start` of the client?

**Comment by dapplion** [comment]
> @dapplion @ajsantander is this still relevant during `start` of the client?

Probably yes, this will be something to take into account regardless of the implementation

**Comment by ajsantander** [comment]
Implementing this on the next release of the Buidler plugin. This should be enough to close the issue, since we're moving all development to the plugin.

The plugin will now:
1) Check the integrity local client version. The check is simple, but could be improved in the future. It looks for an index.html in the build folder.
2) If 1 fails, it will delete the entire directory and install it again.
3) All the sub-processes of the installation (cloning, module installation, and building) are verified. If any of these fail, an attempt to delete the entire directory is made and an error is thrown.

This guarantees that errors thrown during an installation are reverted, and gives some guarantee that malformed previous installations will be detected.
