### ISSUE TITLE
Metamask nonce issue

### ISSUE THREAD

**Issue by jtremback** [aragon/aragon-cli#156]
I was running into this issue: https://github.com/MetaMask/metamask-extension/issues/1999

I fixed it with this janky hack: https://github.com/aragon/aragon-cli/pull/155/commits/e2509c221ede7596b2f911d7dac9ca623d897585

Is there a better long term solution?

**Comment by izqui** [comment]
I was missing this context when reviewing #155 and I think my addition to it setting the network id to 15 won't be fixing your problem. This commit should be reverted https://github.com/aragon/aragon-cli/commit/f7c25c15b8ce2ad0bb52425dedd810ff0aeb00d6

Trying to think about the implications of starting with a different network_id every time. I assume that you started noticing the issue after doing a `devchain --reset` (or `run --reset`) and metamask was still trying to send transactions with the cached nonce.

However I don't really understand how your hack may have fixed the issue, as right now every time you run `aragon devchain` the network id changes (if no network id is passed, ganache defaults to setting the current timestamp as the network id).

**Comment by jtremback** [comment]
Yea, what I actually do is run devchain on my modified aragon-cli, and leave it up for a while. This works for a long time. When the nonce issue shows up, I restart devchain and it goes away for another long time.

**Comment by jtremback** [comment]
Also, maybe just restarting devchain was enough and I'm fooling myself into thinking it needed more.

**Comment by izqui** [comment]
Are you running `aragon devchain` directly rather than it being started by `aragon run` every time you execute it?

If that's the case, I think I know what the root of issue may be:
- `aragon devchain` starts the network with a random network id (the timestamp).
- `aragon run` performs some transactions incrementing the nonce of the main account
- Using the app with metamask caches the nonce when performing sending transactions via Metamask
- Doing `aragon run` or any other action that sends transactions from the CLI increments the nonce of the account.
- When using metamask again, it assumes the nonce should be the one it has cached, not being aware that the CLI has sent more transactions.

In order to circumvent the issue you can either not run `aragon devchain` independently and just rely on `aragon run` starting it every time or do a 'Reset Account' in Metamask which will invalidate the nonce cache.

**Comment by izqui** [comment]
@jtremback I investigated the issue a bit more, and I think it is now solved. I brought back your idea of randomizing the network id every time the chain is started (I didn't detect any side effects). Sometimes Metamask is still stuck even if the networkID changes, but switching to another network and then switching back seems to resolve it in all cases.
