### ISSUE TITLE
Why not use truffle to deploy contracts in `aragon deploy`

### ISSUE THREAD

**Issue by atvanguard** [aragon/aragon-cli#188]
[compile contracts](https://github.com/aragon/aragon-cli/blob/master/src/commands/deploy.js#L54) uses truffle to compile contracts [here](https://github.com/aragon/aragon-cli/blob/master/src/helpers/truffle-runner.js#L22).

For deploying contracts, see [here](https://github.com/aragon/aragon-cli/blob/master/src/commands/deploy.js#L60); why roll our own logic instead of simply using truffle?

Use case is I would like `aragon deploy` to pick up the contracts deploy logic from the migrations folder in my truffle project, which can often get complex.

**Comment by atvanguard** [comment]
I think I understand. Is it because we want to attach `contractInstance` and `contract ` to `ctx` variable, so that they can be utilized in the subsequent steps of `aragon run` - and there is no straightforward of getting these values from `truffle migrate`.

If this is indeed true, how do I deploy an aragon app with custom deploy logic? - for instance, let's say I want to deploy another contract and pass the address of the deployed contract to the constructor of my app contract.

**Comment by izqui** [comment]
Because of how aragonOS uses Delegate Proxies for running apps, the base contract of your app that gets published when running `aragon apm publish` is not used directly, but used by proxy contracts as their logic. That causes that whatever state is stored by the constructor of your app, that will not be present in the instances of your app. The parameters you are currently passing as init arguments (we will have to rename those as it can be confusing) are passed to the constructor of the base contract, 

That's why you need to have an `initialize()` function like [this one](https://github.com/aragon/aragon-apps/blob/master/apps/finance/contracts/Finance.sol#L122) in your app that can be used for the things you would use a constructor for. `aragon run` currently doesn't support calling the initialize method in apps, so it needs to be done separately. 

With the new `aragon dao exec` command that [was recently merged](https://github.com/aragon/aragon-cli/pull/141) but still not published, you can call the initialize function in your app instance.

**Comment by atvanguard** [comment]
Understood. Thanks for the quick PR!
