### ISSUE TITLE
Create pre-packaged build of client

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#301]
Related to #203

**Comment by galactusss** [comment]
To solve this issue my plan is:
1. Create a build from the last version of the [client](https://github.com/aragon/aragon)
2. Publish it to ipfs
3. Edit the Open DAO [task](https://github.com/aragon/aragon-cli/blob/master/src/commands/run.js#L248) of aragon run command. This task will:
  3.1 Download from ipfs the pre-build client
  3.2 Omit the task if a pre-build already exist
  3.3 Start the client

@0x6431346e, @Quazia, @sohkai What do you think?

**Comment by 0x6431346e** [comment]
> To solve this issue my plan is:
> 
> 1. Create a build from the last version of the [client](https://github.com/aragon/aragon)
> 2. Publish it to ipfs
> 3. Edit the Open DAO [task](https://github.com/aragon/aragon-cli/blob/master/src/commands/run.js#L248) of aragon run command. This task will:
>    3.1 Download from ipfs the pre-build client
>    3.2 Omit the task if a pre-build already exist
>    3.3 Start the client
> 
> @0x6431346e, @Quazia, @sohkai What do you think?

Having this on IPFS would be awesome! some things to note though: we need to
- automate step 1 and 2 through github actions
- pin the bundle to Aragon's IPFS node (https://ipfs.eth.aragon.network/ipfs) to make sure at least 1 peer has this file
- serve the client with [a simple server](https://www.npmjs.com/package/serve), not the ipfs gateway (see  https://twitter.com/izqui9/status/1061602902693818368)
- fallback to the old git clone + build

Another approach (or a starting point before IPFS) worth mentioning:
- build the client on every push
- add the build folder to git
- when cloning the wrapper check if the build (or dist) folder exists and if yes, serve that, otherwise do the building

Pros: 
- easy
- does not rely on the assumption that the IPFS file will be fast and distributed evenly

Cons:
- PR diffs would not be pretty

**Comment by galactusss** [comment]
Thanks for you answer Daniel it make a lot more sense now

@0x6431346e I have a last question concerning the process of serve the client. Right now you need to run `npm run start:local` this will execute a script that init the local env, copy the aragon-ui components to ./build and use parcel to serve the cliente with:

```
parcel serve src/index.html --port ${clientPort} --out-dir ./build --no-cache
``` 

This will start a server on http://localhost:3000 and build the app 

I'm not sure if this building process could be prevent also or I'm not understanding completely what the bundle meant for the client

**Comment by 0x6431346e** [comment]
We need to support environment variables such as ENS registry, network, port, etc. I'm not sure if we can reuse those scripts or write a new one. 🤔
The idea would be to not need to install any npm dependencies or to compile the project.

**Comment by 0x6431346e** [comment]
I wonder if instead of this we can publish the GUI to `npm`, or if we can download it from APM using IPFS.

The only downside would be that you cannot use any commit/version :man_shrugging:

**Comment by sohkai** [comment]
> Download it from APM using IPFS

This is really cool, and something I hadn't thought about. Yes, this is absolutely the way we should go!

If you want to use a development version of the client, you can clone and start that yourself manually without too much fuss.
