### ISSUE TITLE
Monorepo structure

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#319]
Change the structure of Aragon CLI to be a monorepo. 

Kick off discussion: https://github.com/AragonDAC/create-aragon-app/issues/1

TODO:
- [ ] dao-cmds
- [ ] apm-cmds
- [ ] Ipfs-cmds

**Comment by osarrouy** [comment]
Hey @galactusss 

I'm not sure about Aragen cause i've not dived into its code yet but doesn't it introduce some cyclic dependencies ? Not sure about that. Otherwise i think it makes sense to introduce it in the monorepo as all the CLI related tools will rely on it.

Regarding the monorepo structure i'm not sure either - lots of doubts this morning ;) I definitely find the second version cleaner and really like it. However the last time I tried to play with a non-standard monorepo struct - _i.e._ every packages under the `packages` folder - I ran into a couple of issue. But maybe it was because of my particular monorepo structure. I can't remember to be honest.

Have you tried to mock both of these structures with `lerna` ? Was it fine ?

**Comment by galactusss** [comment]
Thank you for the feedback. I read the same thing, others bumped into problems with an structure similar to the second. Also, 0x have a bunch of package and they are using the first one. So I will go with the first structure. 

I did mock a first basic example in my repo [aragonCLI](https://github.com/galactusss/aragonCLI). I would like to refactor first at something like this. I'm c

**Comment by sohkai** [comment]
> I believe it make sense to include the boilerplates, I found them to be related to the cli at some extend (is aragen also a posible candidate to include as a package?)

I think it might get harder to clone the boilerplates if we included it in a monorepo (don't think it's easy to only clone a particular directory from a repo), so I'd probably leave them out.

aragen would make sense to include in the repo, however its problem is that it has a fairly involved installation phase as well an automated release strategy through merges to master. If we do move it, I'd do it later once we've settled on the structure.

--------

On the `lerna` structure, you'll notice we don't use the "packages" lerna structure in aragon-apps. I don't think naming the directories different makes a big difference, but it's just that they'll be in [different scopes](https://www.npmjs.com/package/@lerna/filter-options#--scope-glob) with lerna usually using "packages" as the default scope.

**Comment by macor161** [comment]
@0xGabi Don't know if you want to reopen this?

**Comment by 0xGabi** [comment]
Yes let's do it to track our progress with v7 on both new dao and apm packages. What you think?

**Comment by 0xGabi** [comment]
Replaced by #826
