### ISSUE TITLE
Support permissions with parameters

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#407]
This issue was funded with **240 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---

**Comment by lkngtn** [comment]
I'm curious how this would look from a user perspective. Would the idea be that you would be able to pass the parameter array from the CLI when using the acl grant command?

In the UI for permissions, would this appear as a normal non-parameterized permission. (this is probably a question for Aragon One since its not CLI related but is important). cc @sohkai @izqui

**Comment by izqui** [comment]
> In the UI for permissions, would this appear as a normal non-parameterized permission.
Yes, we are currently not checking whether a granted permission has parameters when inspecting the ACL.
