### ISSUE TITLE
Include infura:{network} environments

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#421]
This issue was funded with **75 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---
Start using `aragon:local` as default environment. We need to update the environment middleware.

**Comment by 0x6431346e** [comment]
I can't tell if it makes more sense to rename `aragon:local` to `default` or the other way around. 🤔 

I've prepended `aragon:` because `wsRPC` points to our public aragon node and the `registry` points to the "official" deployment that we support. But I can see the signing node points to infura. Maybe we can move from `https://${network}.infura.io` to `https://${network}.eth.aragon.network/`. 

If we do that we could also add some extra environments like `infura:rinkeby`, so when people have nonce issues because the node is out of sync, they have an alternative.

**Comment by 0xGabi** [comment]
I like the more general option. This allow to further extend to more environments, similar to npm namespaces.

**Comment by 0xGabi** [comment]
We have update the node, will leave open to track include infura environments 🤷‍♂️

**Comment by sohkai** [comment]
@0xGabi wondering if it's even worth having these `infura` environments, because the rate throttling is so high without a key, by default it's almost unusable.

Perhaps what we could do instead is offer a tool to make it easier / more obvious to change your arapp.json, so that if you wanted to use Infura with a key, it'd be really easy.

**Comment by 0xGabi** [comment]
Agree, will close this issue and open a new one to track your idea about an `arapp.json` tool
