### ISSUE TITLE
EPIC: Dev-CLI

### ISSUE THREAD

**Issue by chris-remus** [aragon/aragon-cli#68]

**Comment by luisivan** [comment]
Some stuff done during this epic:

[x] Explain what APM is, why you need ENS, etc. Point to doc link in the help of `aragon`
[x] Revert to Truffle commands when used with `aragon contracts` (compile, exec, console)
[x] Connect to existing chain if running
[x] Auto-init IPFS
[x] Auto-init Ganache
[x] No private keys handling
[x] Fill app name in arapp.json
[x] Fix "No front-end detected (no manifest.json)" issue
[x] Stop using keyfile and ethRpc
[x] Exit process, sometimes something hangs on
[x] Listen to stdout on IPFS and Ethereum nodes to know when they're ready, instead of timeouts
[x] Automatically set IPFS CORS headers
[x] Flag to run a headless DAO
[x] See if APM IPFS RPC flags are set and skip install check and just connect
[x] Check if another testrpc instance is running, and if something reverts while fetching the DAOFactory, 
tell the user about aragon run and aragon devchain
[x] process.exit in version command
