### ISSUE TITLE
Initialize every Aragon CLI download with it's own seed phrase

### ISSUE THREAD

**Issue by burrrata** [aragon/aragon-cli#758]
## 💥 Proposal

AFAIK the Aragon CLI uses the same accounts from the same seed phrase for everyone. That's been fine mostly, but today I just tried to deploy a Rinkeby or and realized that the account was out of Rinkeby ETH. My first thought was, whatever I'll just add more. Then it dawned on me that actually anyone could take ownership of my DAO in the middle of my deployment. Even though it's just a Rinkeby test, this is still not good. It would be great if every download of the Aragon CLI came with a unique seed phrase.

**Comment by sohkai** [comment]
I strongly oppose this, because it breaks the UX of how the bundled chain works (it comes with specific accounts holding permissions in already deployed repos / etc).

Rather, the CLI should prompt you to use your own web3 provider (whether that's a `<network>_key.json` file or Frame or etc) when it looks like you're going to do something on a public network.

**Comment by burrrata** [comment]
Didn't know that would break the UX of the devchain package. 

Your suggestion sounds great though as it would totally resolve the Issue. That would be awesome

**Comment by 0xGabi** [comment]
Thanks both @burrrata and @pythonpete32 great feedback. We are currently thinking about this issues and how a roadmap to tackle them looks like, but be sure that improving the web3 providers is in my top priorities right now

**Comment by 0xGabi** [comment]
Also @pythonpete32 not sure if we already make an issue open for creating the `~/.aragon` folder on installation. Would you mind to create one, otherwise? Thanks 🙏
