### ISSUE TITLE
Better error message when we detect a cycle dependency

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#780]
## ❓ Question

This is an issue reported by @dstreppa a couple of days ago that display the following error on the artifact generation step of `apm publish`:
```
There is a cycle in the dependency graph, can't compute topological ordering. Files:
```

I look into it and the issue is related with the `truffle-flattener` dependency that we use to generate the `code.sol` file, [here](https://github.com/aragon/aragon-cli/blob/master/packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js#L155).

Currently there is an [issue open](https://github.com/nomiclabs/truffle-flattener/issues/14) on their repo to tackle this. 

@macor161 @0x6431346e Thoughts?

**Comment by macor161** [comment]
If I'm not mistaken, this would be solved when we upgrade to `truffle 5`. I didn't test it with Aragon though.

**Comment by dstreppa** [comment]
@macor161 currently I am using `truffle 4`

**Comment by macor161** [comment]
@dstreppa Thanks for the info. I thought `truffle 4` didn't support cyclical dependencies, but it turns out it does. I'm afraid this is indeed a problem with `truffle-flattener`. Do you have a link to your project? Maybe we could help you find a quick workaround in the meantime.

**Comment by dstreppa** [comment]
@macor161 here the link https://gitlab.com/supsi-dacd-isaac/asset-manager

**Comment by macor161** [comment]
Thanks @dstreppa . I had a look at your project and I don't think there is an easy fix for to get rid of the cyclic dependency between `Asset` and `SHT`. 

@0xGabi @0x6431346e 
I think it would be worth it eventually to do a quick analysis of the effort necessary to submit a pull request to `truffle-flattener` that would fix their problem.

**Comment by dstreppa** [comment]
Hi, first at all, thank you very much to everybody for the support.

Ok @macor161, I wil try defining `SHT` in `AssetManager`.

I have an idea, if the problem is due to `truffle-flattener` then I could try to bypass it creating only a `sol` file with all the contracts together, an already flattened set of contracts.

Of course this solution is not smart, but if if it works... :wink: What do you think?

And about the usage of `truffle5`, I can try to do it, but the `aragon@cli` installed `truffle4`. Is it possible to integrate `truffle5`?

**Comment by macor161** [comment]
@dstreppa 

> And about the usage of truffle5, I can try to do it, but the aragon@cli installed truffle4. Is it possible to integrate truffle5?

No unfortunately, upgrading to `truffle5` won't solve the problem.

But I thought about it a little bit more yesterday and you could probably simply move the `SHT` contract into `Asset.sol` and this should work.

**Comment by dstreppa** [comment]
Ok, thank you @macor161. Tomorrow I will try

**Comment by 0xGabi** [comment]
>I think it would be worth it eventually to do a quick analysis of the effort necessary to submit a pull request to truffle-flattener that would fix their problem.

Definitely, let's do it. We can keep this issue to track that 👍

**Comment by dstreppa** [comment]
@macor161 I confirm your workaround works! I've just moved `SHT.sol` content appending it to `Asset.sol`.
Thank you very much for the support.

**Comment by sohkai** [comment]
As mentioned in https://github.com/nomiclabs/truffle-flattener/issues/14, generally cyclic dependencies in the same contract are due to bad contract design, and I'd be inclined just to respond with a better error.

For example, one way to solve the problem in https://gitlab.com/supsi-dacd-isaac/asset-manager/ is to abstract the `Asset` (entire or just `getState()`) interface into a solidity `interface` and use that in SHT and Asset.

**Comment by dapplion** [comment]
This "better error message" should instruct the user to resolve the cyclic dependency and suggest for example the usage of common interfaces?

**Comment by 0xGabi** [comment]
I think that should be enough
