### ISSUE TITLE
React boilerplate not getting state updates

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#81]
The counter app does not seem to be getting state updates on increment / decrement despite transactions going through.

**Comment by bingen** [comment]
I just realized that there's a problem with the web3 version used here `1.0.0-beta.21`: events were returned on `error` instead of on `data` here: https://github.com/aragon/aragon.js/blob/master/packages/aragon-wrapper/src/core/proxy/index.js#L29

This comes on `error` (there's nothing wrong, actually)
![screenshot from 2018-05-21 13-02-31](https://user-images.githubusercontent.com/701095/40316938-2cf3c99a-5d20-11e8-83b6-ce754193740a.png)

We should see something like this instead:
![screenshot from 2018-05-21 13-07-35](https://user-images.githubusercontent.com/701095/40317073-9beb9184-5d20-11e8-89f9-56a4c52a7483.png)

I'll submit a PR upgrading to `1.0.0-beta.34`, which worked fine for me and we can discuss there, as @sohkai pointed out that there have been problems before with web3 and that's probably why version is currently pinned to that version.

**Comment by sohkai** [comment]
Fixed in https://github.com/aragon/aragon-react-boilerplate/pull/8.
